[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 2500000
  flush_interval = "1s"
  flush_jitter = "0s"
  omit_hostname = true
  buffer_strategy = "memory"


# CONFIGURATION POUR LA METHODE SQL
# [[inputs.sql]]
#   driver = "flightsql"
#   dsn = "flightsql://token:apiv3_W3Q2EjtfTnJkkxPmXZszrurKFWNUif763KyJJKRCUWMi_z17tVvqjZqR2MHMm0XuZjhgsu40WAXDiJNn0f9ZeQ@influxdb3-enterprise:8181?database=ephemeral"
#   timeout = "30m"

#   [[inputs.sql.query]]
#     query = "SELECT * FROM cnc_data WHERE time >= '2026-06-01T18:47:00.008Z' AND time <= '2026-06-18T18:47:00.008Z'"
#     field_columns_exclude = ['ASSET_UUID', 'ID', 'TYPE', 'TAG']
#     tag_columns_include = ['ASSET_UUID', 'ID', 'TYPE', 'TAG']
#     tag_columns_exclude = ['VALUE']
#     time_column = 'time'
#     field_columns_include = ['VALUE']
#     field_columns_string = ['VALUE']
#     measurement = "cnc_data_telegraf"


# CONFIGURATION POUR LA METHODE CSV AVEC SCRIPT BASH
[[inputs.file]]
  files = ["/tmp/influx_raw.csv"]
  data_format = "csv"
  csv_header_row_count = 1
  
  csv_column_names = ["time", "ASSET_UUID", "ID", "TAG", "TYPE", "VALUE"]
  csv_column_types = ["string", "string", "string", "string", "string", "string"]
  csv_tag_columns = ["ASSET_UUID", "ID", "TAG", "TYPE"]

  csv_timestamp_column = "time"
  csv_timestamp_format = "2006-01-02T15:04:05.999999999"


  csv_measurement_column = "cnc_data"

# Configuration pour les 2 méthodes
[[outputs.influxdb_v2]]
  urls = ["http://influxdb3-enterprise:8181"]
  token = "apiv3_H-odZMINk_hqFynSnPXC5IW5bIIASh171o6QlEBkc0zxtroucN6mNXW3-KgGsYR6PXAvj0D761J2UWvpXrialw"
  organization = ""
  bucket = "lifetime"
  # content_encoding = "gzip"
  # rate_limit_period = "60s"