[agent]
  ## Intervalle de collecte par défaut pour les plugins d'input "polling".
  ## N'affecte pas Kafka qui est en streaming continu, mais obligatoire.
  interval = "10s"

  ## Taille du round-trip pour l'envoi des données vers les outputs (comme InfluxDB).
  metric_batch_size = 5000

  ## Taille maximale du tampon en mémoire (Buffer). 
  ## Si InfluxDB est temporairement inaccessible, Telegraf garde les données en ram.
  metric_buffer_limit = 100000

  ## Fréquence à laquelle Telegraf vide son buffer et envoie les données à InfluxDB,
  ## même si la taille 'metric_batch_size' n'est pas atteinte.
  flush_interval = "10s"

  ## Logs
  debug = false
  quiet = false
  logfile = ""

  # Ne pas enregistrer le nom d'hôte dans les métriques.
  omit_hostname = true

[[inputs.kafka_consumer]]
  brokers = ["broker:9092"]
  topics = ["ASSETS"]
  consumer_group = "telegraf_consumer"
  data_format = "json_v2"

  [[inputs.kafka_consumer.json_v2]]
    # "measurement_name" sera le nom de ta table dans InfluxDB
    measurement_name = "AssetsMetrics"

    # --- CONFIGURATION DES TAGS ---
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "ASSET_UUID"
      rename = "AssetUuid"
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "ID"
      rename = "Id"
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "TYPE"
      rename = "Type"
    [[inputs.kafka_consumer.json_v2.tag]]
      path = "TAG"
      rename = "Tag"

    # --- CONFIGURATION DES FIELDS ---
    [[inputs.kafka_consumer.json_v2.field]]
      path = "VALUE"
      rename = "Value"
      type = "string"

    [[inputs.kafka_consumer.json_v2.field]]
      path = "TIMESTAMP"
      rename = "CreatedAt"
      type = "string"



[[outputs.influxdb_v2]]
  urls = ["http://influxdb3-enterprise:8181"]
  token = ""
  organization = ""
  bucket = "ephemeral"