#!/bin/bash

KSQL_URL="http://localhost:8088/ksql"

FACTORY_STREAM=$(cat <<EOF
CREATE STREAM IF NOT EXISTS FACTORY_ASSETS_STREAM (
    KEY VARCHAR,
    ASSET_UUID VARCHAR,
    ID VARCHAR,
    VALUE VARCHAR,
    TYPE VARCHAR,
    TAG VARCHAR, 
    TIMESTAMP VARCHAR
) WITH (
    KAFKA_TOPIC='ASSETS',
    VALUE_FORMAT='JSON'
);
EOF
)

CNC_STREAM=$(cat <<EOF
CREATE OR REPLACE STREAM CNC_DATA_STREAM 
WITH (
    KAFKA_TOPIC='CNC_DATA',
    VALUE_FORMAT='JSON'
) AS 
SELECT * FROM FACTORY_ASSETS_STREAM 
WHERE ASSET_UUID = 'CNC'
EMIT CHANGES;
EOF
)

DUSTTRAK_STREAM=$(cat <<EOF
CREATE OR REPLACE STREAM DUSTTRAK_DATA_STREAM 
WITH (
    KAFKA_TOPIC='DUSTTRAK_DATA',
    VALUE_FORMAT='JSON'
) AS 
SELECT * FROM FACTORY_ASSETS_STREAM 
WHERE ASSET_UUID = 'DUSTTRAK'
EMIT CHANGES;
EOF
)

for statement in "$FACTORY_STREAM" "$CNC_STREAM" "$DUSTTRAK_STREAM"; do    
    JSON_PAYLOAD=$(jq -n --arg q "$statement" '{ksql: $q}')

    curl -s -X POST \
         -H "Content-Type: application/vnd.ksql.v1+json" \
         -d "$JSON_PAYLOAD" \
         "$KSQL_URL"
    echo -e "\n---"
done