USE labusine_db;
GO

DROP TABLE IF EXISTS Data;
DROP TABLE IF EXISTS Variable;
DROP TABLE IF EXISTS Type;
DROP TABLE IF EXISTS Transform;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS EquipmentType;
DROP TABLE IF EXISTS Manufacturer;
DROP TABLE IF EXISTS Model;
DROP TABLE IF EXISTS Room;

CREATE TABLE Room (
    Id NVARCHAR(255) PRIMARY KEY,
    Nom NVARCHAR(255) NOT NULL,
    Largeur FLOAT NOT NULL,
    Longueur FLOAT NOT NULL,
    Hauteur FLOAT NOT NULL
);

CREATE TABLE EquipmentType (
    Id INT PRIMARY KEY IDENTITY,
    Nom NVARCHAR(255),
    Description TEXT NOT NULL
);

CREATE TABLE Manufacturer (
    Id INT PRIMARY KEY IDENTITY,
    Nom NVARCHAR(255) NOT NULL,
    Description TEXT NOT NULL
);

CREATE TABLE Model (
    Id INT PRIMARY KEY IDENTITY,
    Nom NVARCHAR(255) NOT NULL,
    Description TEXT NOT NULL
);

CREATE TABLE Equipment (
    Id NVARCHAR(255) PRIMARY KEY,
    AssetUuid NVARCHAR(255) NOT NULL,
    ParentEquipmentId NVARCHAR(255) FOREIGN KEY REFERENCES Equipment(Id),
    EquipmentTypeId INT FOREIGN KEY REFERENCES EquipmentType(Id),
    ManufacturerId INT FOREIGN KEY REFERENCES Manufacturer(Id),
    ModelId INT FOREIGN KEY REFERENCES Model(Id),
    RoomId NVARCHAR(255) FOREIGN KEY REFERENCES Room(Id),
    Nom NVARCHAR(255),
    PrefabKey NVARCHAR(255),
    SerialNumber NVARCHAR(255),
    PurchaseDate DATE
);

CREATE TABLE Type (
    Id INT PRIMARY KEY IDENTITY,
    Nom NVARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Subtype NVARCHAR(255)
);

CREATE TABLE Variable (
    Id INT PRIMARY KEY IDENTITY,
    EquipmentId NVARCHAR(255) FOREIGN KEY REFERENCES Equipment(Id),
    Nom NVARCHAR(255) NOT NULL,
    DataItemId NVARCHAR(255) NOT NULL,
    TypeId INT FOREIGN KEY REFERENCES Type(Id)
);

CREATE TABLE Data (
    Id INT PRIMARY KEY IDENTITY,
    VariableId INT FOREIGN KEY REFERENCES Variable(Id),
    Value NVARCHAR(255) NOT NULL,
    Timestamp DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);